image: node:6

pages:
  stage: deploy
  script:
    - npm install
    - npm run make
    - mkdir public
    - cp view/index.html view/bundle_*.js public/
    - mkdir grafos
    - cp *.xml grafos/
  artifacts:
    paths:
      - public
      - grafos
  cache:
    paths:
      - node_modules
